name: flutter-learning
description: Just a flutter project for learning purposes

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  dio: ^6.1.2
  freezed_annotation: ^2.3.0
  json_annotation: ^6.7.0
  flutter_staggered_animations: ^1.1.0
  intl: ^0.18.0

  dev_dependencies:
    build_runner: ^2.5.0
    freezed: ^2.5.0
    json_serializable: ^6.7.0